---
# tasks file for jenkins
#
- name: "Copying Jdk file to jenkins Node"
  copy:
    src: "/etc/ansible/roles/jenkins/files/jdk-8u221-linux-x64.rpm"
    dest: "/root/"
  ignore_errors: yes

- name: "Copying Jenkins file to jenkins Node"
  copy:
    src: "/etc/ansible/roles/jenkins/files/jenkins-2.281-1.1.noarch.rpm"
    dest: "/root/"
  ignore_errors: yes

- name: "Installing JDK"
  shell: "rpm -ivh /root/jdk-8u221-linux-x64.rpm"
  ignore_errors: yes
  register: jdk
- debug:
     var: jdk.stdout_lines

- name: "Installing Jenkins"
  shell: "rpm -ivh /root/jenkins-2.281-1.1.noarch.rpm"
  ignore_errors: yes
  register: jenkins
- debug:
     var: jenkins.stdout_lines

- name: "Starting Jenkins Server"
  shell: "systemctl start jenkins"
